# Generated by Django 3.0.7 on 2020-06-07 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Capitan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=64)),
                ('apellidos', models.CharField(max_length=64)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CapitanComuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitanOnCapitanComuna', to='servinformacionapp.Capitan')),
            ],
        ),
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=64)),
                ('apellidos', models.CharField(max_length=64)),
                ('telefono', models.IntegerField()),
                ('capitan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitanOnLider', to='servinformacionapp.Capitan')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('direccion', models.CharField(max_length=64)),
                ('municipio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipioOnPuesto', to='servinformacionapp.Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Votante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=64)),
                ('apellidos', models.CharField(max_length=64)),
                ('direccion', models.CharField(max_length=64)),
                ('telefono', models.IntegerField()),
                ('id_documento', models.IntegerField()),
                ('mesa', models.IntegerField()),
                ('barrio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barrioOnVotante', to='servinformacionapp.Barrio')),
                ('lider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liderOnVotante', to='servinformacionapp.Lider')),
                ('puesto_votacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puestpOnVotante', to='servinformacionapp.Puesto')),
            ],
        ),
        migrations.CreateModel(
            name='LiderREsponsableBarrios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barrioOnLiderREsponsableBarrio', to='servinformacionapp.Barrio')),
                ('capitan_comuna_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitanComunaOnLiderREsponsableBarrio', to='servinformacionapp.CapitanComuna')),
                ('lider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liderOnLiderREsponsableBarrio', to='servinformacionapp.Lider')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('municipio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipioOnComuna', to='servinformacionapp.Municipio')),
            ],
        ),
        migrations.AddField(
            model_name='capitancomuna',
            name='comuna_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunaOnCapitanComuna', to='servinformacionapp.Comuna'),
        ),
        migrations.AddField(
            model_name='barrio',
            name='comuna_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunaOnBarrio', to='servinformacionapp.Comuna'),
        ),
    ]
